version: 0.2

env:
  variables:
    NODE_ENV: "${env}"

  parameter-store:
    REACT_APP_INTER_PRISON_TRANSFER_MAP_BOX_KEY: REACT_APP_INTER_PRISON_TRANSFER_MAP_BOX_KEY
    REACT_APP_MAP_BOX_STYLE_ID: REACT_APP_MAP_BOX_STYLE_ID
    REACT_APP_INTER_PRISON_TRANSFERS_CLOUD_STORAGE: REACT_APP_INTER_PRISON_TRANSFERS_CLOUD_STORAGE
  
  exported-variables:
    - REACT_APP_INTER_PRISON_TRANSFER_MAP_BOX_KEY
    - REACT_APP_MAP_BOX_STYLE_ID
    - REACT_APP_INTER_PRISON_TRANSFERS_CLOUD_STORAGE

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing . . .
      - yarn install      
  build:
    commands:
      - echo Starting build . . .
      - yarn run build
artifacts:
  files:
    - '**/*'
  name: "web-dist-$(date +%Y-%m-%d)"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*
